server:
    port: 8005
    servlet:
        session:
            timeout: 7200
            cookie:
                max-age: 3600
spring:
    application:
        name: eclub-service
        #SpringMVC上传文件配置
    servlet:
        multipart:
            #默认支持文件上传.
            enabled: true
            #支持文件写入磁盘.
            file-size-threshold: 0
            # 上传文件的临时目录
            location:
            # 最大支持文件大小
            max-file-size: 2MB
            # 最大支持请求大小
            max-request-size: 5MB
    datasource:
        druid:
            url: jdbc:mysql://47.112.190.215:3306/eclub?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
            username: eclub
            password: eclub2020
            driverClassName: com.mysql.cj.jdbc.Driver
            initialSize: 5                          #初始建立连接数量
            minIdle: 5                              #最小连接数量
            maxActive: 100                          #最大连接数量
            maxWait: 10000                          #获取连接最大等待时间，毫秒
            testOnBorrow: true                      #申请连接时检测连接是否有效
            testOnReturn: false                     #归还连接时检测连接是否有效
            timeBetweenEvictionRunsMillis: 60000    #配置间隔检测连接是否有效的时间（ms）
            minEvictableIdleTimeMillis: 300000      #连接在连接池的最小生存时间（ms）
    http:
        encoding:
            force-response: true
    redis:
        port: 6379
        password: eclub2020
        host: 47.112.190.215
        lettuce:
            pool:
                max-active: 200         # 连接池最大连接数（使用负值表示没有限制）
                max-idle: 8             # 连接池中的最大空闲连接
                min-idle: 0             # 连接池中的最小空闲连接
                max-wait: 1000          # 连接池最大阻塞等待时间（使用负值表示没有限制）
            shutdown-timeout: 100       # 超时连接关闭
eclub:
    imgDomain: http://47.112.190.215/
    auth:
        appId: wx13ba688635e7624e
        appSecret: cb8fc6b10933ad71eb4641d422764522
mybatis:
    configuration:
        map-underscore-to-camel-case: true
fdfs:
    # 链接超时
    connect-timeout: 6000
    # 读取时间
    so-timeout: 6000
    # 生成缩略图参数
    thumb-image:
        width: 150
        height: 150
    tracker-list: 47.112.190.215:22122