server:
<<<<<<< HEAD
    port: 9000
    servlet:
        session:
            timeout: 7200
            cookie:
                max-age: 3600
=======
    port: 8090
>>>>>>> 891dbac1af2bd4dab5dab4711cdb1634c9389653
spring:
    application:
        name: eclub-service
    datasource:
        druid:
            url: jdbc:mysql://localhost:3306/eclub?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
            username: root
            password: 123456
            driverClassName: com.mysql.cj.jdbc.Driver
            initialSize: 5  #初始建立连接数量
            minIdle: 5  #最小连接数量
            maxActive: 100 #最大连接数量
            maxWait: 10000  #获取连接最大等待时间，毫秒
            testOnBorrow: true #申请连接时检测连接是否有效
            testOnReturn: false #归还连接时检测连接是否有效
            timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（ms）
<<<<<<< HEAD
            minEvictableIdleTimeMillis: 300000  #连接在连接池的最小生存时间（ms）
=======
            minEvictableIdleTimeMillis: 300000  #连接在连接池的最小生存时间（ms）
    http:
        encoding:
            force-response: true
>>>>>>> 891dbac1af2bd4dab5dab4711cdb1634c9389653
